#!/bin/sh
#PBS -A s5692
#PBS -W group_list=s5692 
#PBS -l select=1:ncpus=24:mem=8gb
#PBS -l walltime=70:00:00
#PBS -N coastline
#PBS -o out1
#PBS -j oe
#PBS -M chunlidai1@gmail.com
#PBS -m abe
#PBS -q ldan 
#PBS -P high

cd $PBS_O_WORKDIR

echo ls /u/cdai/codec2/
ls /u/cdai/codec2/

#module load pkgsrc  #gdalinfo

source /nobackupp17/elarour/coastlinedata/code/miniconda3/bin/activate /nobackupp17/elarour/coastlinedata/code/miniconda3/envs/pgc

python /nobackupp17/elarour/coastlinedata/code/imagery_utils/pgc_ortho.py /u/cdai/elarour/coastlinedata/imagery_by_region/arcticdem_34_alaska_north/ ~/work/orthorectwork/arcticdem_34_alaska_north  --dem /nobackupp17/elarour/coastlinedata/EGM2008_Arctic.tif --epsg 3413 --outtype UInt16 --stretch ns --resample near --no-pyramids --parallel-processes 24 

#revise ncpus, parallel-processes, <input_imagery_dir>, <output_ortho_dir>
